from PyQt5 import QtCore, QtWidgets
class Ui_HataguWater1DialogBase(object):
    def setupUi(self, D):
        D.setObjectName("HataguWater1DialogBase")
        D.resize(400, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(D)
        self.comboPolygonLayer = QtWidgets.QComboBox(D)
        self.comboPolygonLayer.setObjectName("comboPolygonLayer")
        self.verticalLayout.addWidget(self.comboPolygonLayer)
        self.comboAttributeField = QtWidgets.QComboBox(D)
        self.comboAttributeField.setObjectName("comboAttributeField")
        self.verticalLayout.addWidget(self.comboAttributeField)
        self.comboPointLayer = QtWidgets.QComboBox(D)
        self.comboPointLayer.setObjectName("comboPointLayer")
        self.verticalLayout.addWidget(self.comboPointLayer)
        self.tableFacilities = QtWidgets.QTableWidget(D)
        self.tableFacilities.setColumnCount(2)
        self.tableFacilities.setHorizontalHeaderLabels(["項目", "点数"])
        self.verticalLayout.addWidget(self.tableFacilities)
        self.buttonRowLayout = QtWidgets.QHBoxLayout()
        self.buttonAddRow = QtWidgets.QPushButton("追加")
        self.buttonRemoveRow = QtWidgets.QPushButton("削除")
        self.buttonRowLayout.addWidget(self.buttonAddRow)
        self.buttonRowLayout.addWidget(self.buttonRemoveRow)
        self.verticalLayout.addLayout(self.buttonRowLayout)
        self.lineOutputName = QtWidgets.QLineEdit(D)
        self.verticalLayout.addWidget(self.lineOutputName)
        self.buttonRun = QtWidgets.QPushButton("実行")
        self.verticalLayout.addWidget(self.buttonRun)
        QtCore.QMetaObject.connectSlotsByName(D)
